### ISSUE TITLE
[minor] Update package.json to reflect other services.

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-tournament#1]
Typically we want a `quick-test` or a `quick-start` in our services to run the command without building. This is very useful for built docker images. That way we can just run `npm run quick-start` in the Dockerfile CMD line. 

Typically if we are running it manually, we are testing it, where building on `npm run start` is preffered.

Basically we want all of our services to act the same way.

**Comment by user404d** [comment]
outdated
